### Simple Arithmetic

You could use arithmetic operators `+` `-` `*` `/` directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.

In [13]:
# importing the modules
import numpy as np

# creating the two arrays
arr1 = np.array([15, 13, 8, 30, 20, 32])
arr2 = np.array([61, 96, 63, 93, 20, 42])

In [2]:
np.add(arr1, arr2)

array([ 76, 109,  71, 123,  40,  74])

In [3]:
np.subtract(arr1, arr2)

array([-46, -83, -55, -63,   0, -10])

In [4]:
np.multiply(arr1, arr2)

array([ 915, 1248,  504, 2790,  400, 1344])

In [5]:
np.divide(arr1, arr2)

array([0.24590164, 0.13541667, 0.12698413, 0.32258065, 1.        ,
       0.76190476])

In [7]:
np.power(arr1, arr2)

array([ 1140014543, -1906587263,           0,           0,           0,
                 0])

In [10]:
np.absolute(arr1)

array([15, 13,  8, 30, 20, 32])

In [14]:
np.absolute(arr2)

array([61, 96, 63, 93, 20, 42])

In [15]:
np.divmod(arr1, arr2)

(array([0, 0, 0, 0, 1, 0]), array([15, 13,  8, 30,  0, 32]))

In [16]:
np.mod(arr1, arr2)

array([15, 13,  8, 30,  0, 32])

In [17]:
np.remainder(arr1, arr2)

array([15, 13,  8, 30,  0, 32])