In [1]:
import numpy as np

In [3]:
np.prod([12, 31, 32])

11904

In [5]:
np.prod([[12, 12, 31], [12, 12, 43]])

27641088

In [7]:
np.prod([[12, 12, 31], [12, 12, 43]], axis=1)

array([4464, 6192])

In [9]:
np.cumprod([[12, 12, 31], [12, 12, 43]])

array([      12,      144,     4464,    53568,   642816, 27641088])

In [10]:
np.cumprod([[12, 12, 31], [12, 12, 43]], axis=1)

array([[  12,  144, 4464],
       [  12,  144, 6192]])