In [1]:
# importing the modules

import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### types of Array
    1. 0D array
    2. 1D array
    3. 2D array
    4. 3D array

## 0D Array

In [5]:
arr = np.array(42)
print("Array: ", arr)
print("type: ", type(arr))
print("Dimension: ", arr.ndim)

Array:  42
type:  <class 'numpy.ndarray'>
Dimension:  0


## 1D Array

In [3]:
array1 = np.array([1, 2, 3, 4, 5])
print("Array: ", array1)
print("type: ", type(array1))
print("Dimension: ", array1.ndim)

Array:  [1 2 3 4 5]
type:  <class 'numpy.ndarray'>
Dimension:  1


## 2D Array

In [6]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Array: ", arr)
print("type: ", type(arr))
print("Dimension: ", arr.ndim)

Array:  [[1 2 3]
 [4 5 6]]
type:  <class 'numpy.ndarray'>
Dimension:  2


## 3D Array

In [8]:
arr = np.array([
    [
        [1, 2, 3]
    ],
    [
        [4, 5, 6]
    ]
])
print("Array: ", arr)
print("type: ", type(arr))
print("Dimension: ", arr.ndim)

Array:  [[[1 2 3]]

 [[4 5 6]]]
type:  <class 'numpy.ndarray'>
Dimension:  3


## Random Dimension Array

In [11]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print("Array: ", arr)
print("type: ", type(arr))
print("Dimension: ", arr.ndim)

Array:  [[[[[1 2 3 4 5]]]]]
type:  <class 'numpy.ndarray'>
Dimension:  5


In [12]:
arr = np.array([1, 2, 3, 4, 5], ndmin=10)
print("Array: ", arr)
print("type: ", type(arr))
print("Dimension: ", arr.ndim)

Array:  [[[[[[[[[[1 2 3 4 5]]]]]]]]]]
type:  <class 'numpy.ndarray'>
Dimension:  10
