## Reshaping arrays

* Reshaping means changing the shape of an array.
* The shape of an array is the number of elements in each dimension.
* By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [2]:
# importing the modules
import numpy as np

# creating the array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [3]:
print(f"arr.shape = {arr.shape}")
print(f"arr.ndim = {arr.ndim}")

arr.shape = (12,)
arr.ndim = 1


### changing the 1D to 2D

In [4]:
print(f"arr.reshape(2, 6) = {arr.reshape(2, 6)}")

arr.reshape(2, 6) = [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### changing 1D to 3D 

In [5]:
print(f"arr.reshpe(2, 3, 2) = {arr.reshape(2, 3, 2)}")

arr.reshpe(2, 3, 2) = [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### checking it return the copy or view

In [7]:
print(f"copy or view for arr.reshape(2, 6).base = {arr.reshape(2, 6).base}")

copy or view for arr.reshape(2, 6).base = [ 1  2  3  4  5  6  7  8  9 10 11 12]


so reshape will be considered as view

### unknown dimension

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr.reshape(3, 3, -1))

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


### flattering the array

*the **`any`** dimension array into **`1D`** array*

In [11]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,0]
])
print(f"arr = {arr}")
print(f"arr.reshape(-1) = {arr.reshape(-1)}")

arr = [[1 2 3 4 5]
 [6 7 8 9 0]]
arr.reshape(-1) = [1 2 3 4 5 6 7 8 9 0]
