## Iterating Arrays

*Iterating means going through elements one by one.*

In [1]:
# importing the module
import numpy as np

# creating the arrays
arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
arr2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 0]
])
arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

### iterating 1D Array

In [5]:
print(f"1D arr :\n{arr1d}")

print("\nArray items\n")
for i in arr1d:
    print(i, end=' ')

1D arr :
[1 2 3 4 5 6 7 8 9 0]

Array items

1 2 3 4 5 6 7 8 9 0 

### iterating 2D Array

In [10]:
print(f"2D arr: \n{arr2d}")

print("\nArray items\n")
for i in arr2d:
    print(i, end=' ')
    
print("\n\nArray items\n")
for i in arr2d:
    for j in i:
        print(j, end=' ')

2D arr: 
[[1 2 3 4 5]
 [6 7 8 9 0]]

Array items

[1 2 3 4 5] [6 7 8 9 0] 

Array items

1 2 3 4 5 6 7 8 9 0 

### iterating 3D Array

In [12]:
print(f"3D arr: \n{arr3d}")

print("\nArray items\n")
for i in arr3d:
    print(i, end=' ')
    
print("\n\nArray items\n")
for i in arr3d:
    for j in i:
        print(j, end=' ')
        
print("\n\nArray items\n")
for i in arr3d:
    for j in i:
        for k in j:
            print(k, end=' ')

3D arr: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Array items

[[1 2 3]
 [4 5 6]] [[ 7  8  9]
 [10 11 12]] 

Array items

[1 2 3] [4 5 6] [7 8 9] [10 11 12] 

Array items

1 2 3 4 5 6 7 8 9 10 11 12 

### Iterating Arrays Using nditer()

*The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.*

#### Iterating on Each `Scalar` Element

In basic `for` loops, iterating through each scalar of an array we need to use '`n`' for loops which can be difficult to write for arrays with very high dimensionality.

In [14]:
print(arr1d)

[1 2 3 4 5 6 7 8 9 0]


In [16]:
for i in np.nditer(arr1d):
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 0 

In [17]:
print(arr2d)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [18]:
for i in np.nditer(arr2d):
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 0 

In [19]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [20]:
for i in np.nditer(arr3d):
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [34]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=[float]):
    print(x, end=',   \t')

1.0,   	2.0,   	3.0,   	

In [36]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x, end='\t')

1	3	5	7	

### Enumerated Iteration Using ndenumerate()

*Enumeration means mentioning sequence number of somethings one by one.*

Sometimes we require corresponding index of the element while iterating, the '`ndenumerate()`' method can be used for those usecases.

In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(f"arr = {arr}")

arr = [1 2 3 4 5 6 7 8 9 0]


In [40]:
for index, value in np.ndenumerate(arr):
    print(f"{index}. {value}")

(0,). 1
(1,). 2
(2,). 3
(3,). 4
(4,). 5
(5,). 6
(6,). 7
(7,). 8
(8,). 9
(9,). 0


In [41]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f"arr = {arr}")

arr = [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
for index, value in np.ndenumerate(arr):
    print(f"{index}. {value}")

(0, 0). 1
(0, 1). 2
(0, 2). 3
(1, 0). 4
(1, 1). 5
(1, 2). 6
(2, 0). 7
(2, 1). 8
(2, 2). 9
