### Searching Arrays

*You can search an array for a certain value, and return the indexes that get a match.*

To search an array, use the `where()` method.

In [1]:
# importing the modules
import numpy as np

# creating the array
arr = np.array([1, 2, 3, 4, 5])

In [2]:
np.where(arr == 4)

(array([3], dtype=int64),)

In [3]:
np.where(arr%2 == 0)

(array([1, 3], dtype=int64),)

### Search Sorted

There is a method called `searchsorted()` which performs a *`binary search`* in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [4]:
np.searchsorted(arr, 3)

2

In [5]:
np.searchsorted(arr, 2)

1

In [6]:
np.searchsorted(arr, 10)

5

In [7]:
np.searchsorted(arr, 1000)

5

In [9]:
np.searchsorted(arr, 2, side='right')

2

In [10]:
np.searchsorted(arr, [1, 3])

array([0, 2], dtype=int64)