### Sorting Arrays

*Sorting means putting elements in an ordered sequence.*

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, *ascending* or *descending*.

The NumPy ndarray object has a function called `sort()`, that will sort a specified array.

In [1]:
# importing the modules
import numpy as np

# creating the arrays
arr = np.array([10, 29, 3, 19, 21, 31, 12, 22])

In [2]:
print(f"arr = {arr}")

arr = [10 29  3 19 21 31 12 22]


In [3]:
np.sort(arr)

array([ 3, 10, 12, 19, 21, 22, 29, 31])

In [8]:
alphabets = np.array(['b', 's', 'e', 'a', 'h', 't', 'k', 'm'])

In [9]:
print(f'alphabets = {alphabets}')

alphabets = ['b' 's' 'e' 'a' 'h' 't' 'k' 'm']


In [10]:
np.sort(alphabets)

array(['a', 'b', 'e', 'h', 'k', 'm', 's', 't'], dtype='<U1')

## sorting the 2D array

In [11]:
arr = np.array([
    [1, 5, 2],
    [9, 3, 8]
])
print(f"arr = {arr}")

arr = [[1 5 2]
 [9 3 8]]


In [12]:
np.sort(arr)

array([[1, 2, 5],
       [3, 8, 9]])